Revert "kie-editors from 0.9.0 (29.3 MB) to 0.10.0 (12.3 MB)"
Not working on both Chrome and Firefox
Multiple error in the console.
Initialization on FF:
SEVERE [LogConfiguration] DataCloneError: The object could not be cloned. srcdoc line 9 > injectedScript:1:1798
Error: JsException: DataCloneError: The object could not be cloned.
e.exports</i</e.prototype.send@about:srcdoc:72:121547
e/this.manager<@about:srcdoc:72:120837
e.exports</i</e.prototype.respond@about:srcdoc:72:118422
e.exports</i</e.prototype.receive@about:srcdoc:72:119840
receive@about:srcdoc:72:117246
e.exports</i</e.prototype.receive@about:srcdoc:72:121896
e.exports</i</e.prototype.startListening/this.eventListener@about:srcdoc:72:121203
EventListener.handleEvent*e.exports</i</e.prototype.startListening@about:srcdoc:72:121229
e.exports</l</e.prototype.start/</<@about:srcdoc:72:114247
l/</<@about:srcdoc:72:113410
l/<@about:srcdoc:72:113515
i@about:srcdoc:72:112229
promise callback*c@about:srcdoc:72:112394
e.exports</o</<@about:srcdoc:72:112405
e.exports</o<@about:srcdoc:72:112172
e.exports</l</e.prototype.start@about:srcdoc:72:114002
e.exports</f</e.prototype.start@about:srcdoc:43:46052
u@about:srcdoc:43:28946
a@about:srcdoc:82:6037
@about:srcdoc:82:6347
EventListener.handleEvent*@about:srcdoc:82:6299
n@about:srcdoc:28:110
@about:srcdoc:28:902
@about:srcdoc:28:913
srcdoc line 9 > injectedScript:1:1798
Uncaught DOMException: The object could not be cloned. srcdoc:82

BPMN Load:
Uncaught (in promise) TypeError: Cannot read property 'trim' of undefined
    at t.e.setContent (about:srcdoc:82)
    at t.receive_contentChanged (about:srcdoc:43)
    at e.receive (about:srcdoc:72)
    at Object.receive (about:srcdoc:72)
    at e.receive (about:srcdoc:72)
    at eventListener.eventListener (about:srcdoc:72)

This reverts commit 23c3c6ca